const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7c6ef0",
    background: "#f8f7ff",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#7c6ef0",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#1a1a3e",
    muted: "#f3f1ff",
    mutedForeground: "#6b6b8a",
    accent: "#4f3df5",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e0ddf7",
    input: "#e0ddf7",
    success: "#22c55e",
    warning: "#f59e0b",
    live: "#ef4444",
    gold: "#f59e0b",
  },
  dark: {
    text: "#f4f3ff",
    tint: "#7c6ef0",
    background: "#0f0e1a",
    foreground: "#f4f3ff",
    card: "#141228",
    cardForeground: "#f4f3ff",
    primary: "#7c6ef0",
    primaryForeground: "#ffffff",
    secondary: "#1e1b35",
    secondaryForeground: "#c4c1e8",
    muted: "#1e1b35",
    mutedForeground: "#9090a8",
    accent: "#4f3df5",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2647",
    input: "#2a2647",
    success: "#22c55e",
    warning: "#f59e0b",
    live: "#ef4444",
    gold: "#f59e0b",
  },
  radius: 12,
};

export default colors;
