/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Swayam Shiksha API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ActivityItem,
  AuthUser,
  Category,
  Course,
  CourseDetail,
  CreateCategoryBody,
  CreateCourseBody,
  CreateDppBody,
  CreateLiveStreamBody,
  CreatePdfBody,
  CreateTestSeriesBody,
  CreateVideoBody,
  DashboardStats,
  Dpp,
  EnrollBody,
  Enrollment,
  ErrorResponse,
  HealthStatus,
  ListCoursesParams,
  ListTestSeriesParams,
  LiveStream,
  LoginBody,
  Pdf,
  RegisterBody,
  SuccessResponse,
  TestSeries,
  TestSeriesDetail,
  UpdateCategoryBody,
  UpdateCourseBody,
  UpdateLiveStreamBody,
  Video,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const getRegisterUrl = () => {
  return `/api/auth/register`;
};

export const register = async (
  registerBody: RegisterBody,
  options?: RequestInit,
): Promise<AuthUser> => {
  return customFetch<AuthUser>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerBody),
  });
};

export const getRegisterMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: BodyType<RegisterBody> }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<RegisterBody>;
export type RegisterMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new user
 */
export const useRegister = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options));
};

/**
 * @summary Login
 */
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

export const login = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthUser> => {
  return customFetch<AuthUser>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginBody>;
export type LoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login
 */
export const useLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};

/**
 * @summary Logout
 */
export const getLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const logout = async (
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout
 */
export const useLogout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<AuthUser> => {
  return customFetch<AuthUser>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all categories
 */
export const getListCategoriesUrl = () => {
  return `/api/categories`;
};

export const listCategories = async (
  options?: RequestInit,
): Promise<Category[]> => {
  return customFetch<Category[]>(getListCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCategoriesQueryKey = () => {
  return [`/api/categories`] as const;
};

export const getListCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategories>>> = ({
    signal,
  }) => listCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCategories>>
>;
export type ListCategoriesQueryError = ErrorType<unknown>;

/**
 * @summary List all categories
 */

export function useListCategories<
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a category (admin)
 */
export const getCreateCategoryUrl = () => {
  return `/api/categories`;
};

export const createCategory = async (
  createCategoryBody: CreateCategoryBody,
  options?: RequestInit,
): Promise<Category> => {
  return customFetch<Category>(getCreateCategoryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCategoryBody),
  });
};

export const getCreateCategoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: BodyType<CreateCategoryBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: BodyType<CreateCategoryBody> },
  TContext
> => {
  const mutationKey = ["createCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategory>>,
    { data: BodyType<CreateCategoryBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createCategory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCategory>>
>;
export type CreateCategoryMutationBody = BodyType<CreateCategoryBody>;
export type CreateCategoryMutationError = ErrorType<unknown>;

/**
 * @summary Create a category (admin)
 */
export const useCreateCategory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: BodyType<CreateCategoryBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: BodyType<CreateCategoryBody> },
  TContext
> => {
  return useMutation(getCreateCategoryMutationOptions(options));
};

/**
 * @summary Get a category
 */
export const getGetCategoryUrl = (id: number) => {
  return `/api/categories/${id}`;
};

export const getCategory = async (
  id: number,
  options?: RequestInit,
): Promise<Category> => {
  return customFetch<Category>(getGetCategoryUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetCategoryQueryKey = (id: number) => {
  return [`/api/categories/${id}`] as const;
};

export const getGetCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategory>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCategory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoryQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategory>>> = ({
    signal,
  }) => getCategory(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCategoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategory>>
>;
export type GetCategoryQueryError = ErrorType<unknown>;

/**
 * @summary Get a category
 */

export function useGetCategory<
  TData = Awaited<ReturnType<typeof getCategory>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCategory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCategoryQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a category (admin)
 */
export const getUpdateCategoryUrl = (id: number) => {
  return `/api/categories/${id}`;
};

export const updateCategory = async (
  id: number,
  updateCategoryBody: UpdateCategoryBody,
  options?: RequestInit,
): Promise<Category> => {
  return customFetch<Category>(getUpdateCategoryUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCategoryBody),
  });
};

export const getUpdateCategoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategory>>,
    TError,
    { id: number; data: BodyType<UpdateCategoryBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: number; data: BodyType<UpdateCategoryBody> },
  TContext
> => {
  const mutationKey = ["updateCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCategory>>,
    { id: number; data: BodyType<UpdateCategoryBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCategory(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCategory>>
>;
export type UpdateCategoryMutationBody = BodyType<UpdateCategoryBody>;
export type UpdateCategoryMutationError = ErrorType<unknown>;

/**
 * @summary Update a category (admin)
 */
export const useUpdateCategory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategory>>,
    TError,
    { id: number; data: BodyType<UpdateCategoryBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: number; data: BodyType<UpdateCategoryBody> },
  TContext
> => {
  return useMutation(getUpdateCategoryMutationOptions(options));
};

/**
 * @summary Delete a category (admin)
 */
export const getDeleteCategoryUrl = (id: number) => {
  return `/api/categories/${id}`;
};

export const deleteCategory = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteCategoryUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCategoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCategory(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategory>>
>;

export type DeleteCategoryMutationError = ErrorType<unknown>;

/**
 * @summary Delete a category (admin)
 */
export const useDeleteCategory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteCategoryMutationOptions(options));
};

/**
 * @summary List courses
 */
export const getListCoursesUrl = (params?: ListCoursesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/courses?${stringifiedParams}`
    : `/api/courses`;
};

export const listCourses = async (
  params?: ListCoursesParams,
  options?: RequestInit,
): Promise<Course[]> => {
  return customFetch<Course[]>(getListCoursesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListCoursesQueryKey = (params?: ListCoursesParams) => {
  return [`/api/courses`, ...(params ? [params] : [])] as const;
};

export const getListCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof listCourses>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCoursesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCourses>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCoursesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCourses>>> = ({
    signal,
  }) => listCourses(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCourses>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCourses>>
>;
export type ListCoursesQueryError = ErrorType<unknown>;

/**
 * @summary List courses
 */

export function useListCourses<
  TData = Awaited<ReturnType<typeof listCourses>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCoursesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCourses>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCoursesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a course (admin)
 */
export const getCreateCourseUrl = () => {
  return `/api/courses`;
};

export const createCourse = async (
  createCourseBody: CreateCourseBody,
  options?: RequestInit,
): Promise<Course> => {
  return customFetch<Course>(getCreateCourseUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCourseBody),
  });
};

export const getCreateCourseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: BodyType<CreateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: BodyType<CreateCourseBody> },
  TContext
> => {
  const mutationKey = ["createCourse"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCourse>>,
    { data: BodyType<CreateCourseBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createCourse(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCourse>>
>;
export type CreateCourseMutationBody = BodyType<CreateCourseBody>;
export type CreateCourseMutationError = ErrorType<unknown>;

/**
 * @summary Create a course (admin)
 */
export const useCreateCourse = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: BodyType<CreateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: BodyType<CreateCourseBody> },
  TContext
> => {
  return useMutation(getCreateCourseMutationOptions(options));
};

/**
 * @summary Get a course with content summary
 */
export const getGetCourseUrl = (id: number) => {
  return `/api/courses/${id}`;
};

export const getCourse = async (
  id: number,
  options?: RequestInit,
): Promise<CourseDetail> => {
  return customFetch<CourseDetail>(getGetCourseUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetCourseQueryKey = (id: number) => {
  return [`/api/courses/${id}`] as const;
};

export const getGetCourseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCourse>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCourseQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourse>>> = ({
    signal,
  }) => getCourse(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetCourseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCourse>>
>;
export type GetCourseQueryError = ErrorType<unknown>;

/**
 * @summary Get a course with content summary
 */

export function useGetCourse<
  TData = Awaited<ReturnType<typeof getCourse>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCourse>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCourseQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a course (admin)
 */
export const getUpdateCourseUrl = (id: number) => {
  return `/api/courses/${id}`;
};

export const updateCourse = async (
  id: number,
  updateCourseBody: UpdateCourseBody,
  options?: RequestInit,
): Promise<Course> => {
  return customFetch<Course>(getUpdateCourseUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCourseBody),
  });
};

export const getUpdateCourseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCourse>>,
    TError,
    { id: number; data: BodyType<UpdateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: BodyType<UpdateCourseBody> },
  TContext
> => {
  const mutationKey = ["updateCourse"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCourse>>,
    { id: number; data: BodyType<UpdateCourseBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCourse(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCourse>>
>;
export type UpdateCourseMutationBody = BodyType<UpdateCourseBody>;
export type UpdateCourseMutationError = ErrorType<unknown>;

/**
 * @summary Update a course (admin)
 */
export const useUpdateCourse = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCourse>>,
    TError,
    { id: number; data: BodyType<UpdateCourseBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: BodyType<UpdateCourseBody> },
  TContext
> => {
  return useMutation(getUpdateCourseMutationOptions(options));
};

/**
 * @summary Delete a course (admin)
 */
export const getDeleteCourseUrl = (id: number) => {
  return `/api/courses/${id}`;
};

export const deleteCourse = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteCourseUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCourseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCourse"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCourse>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCourse(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCourse>>
>;

export type DeleteCourseMutationError = ErrorType<unknown>;

/**
 * @summary Delete a course (admin)
 */
export const useDeleteCourse = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteCourseMutationOptions(options));
};

/**
 * @summary List videos for a course
 */
export const getListVideosUrl = (courseId: number) => {
  return `/api/courses/${courseId}/videos`;
};

export const listVideos = async (
  courseId: number,
  options?: RequestInit,
): Promise<Video[]> => {
  return customFetch<Video[]>(getListVideosUrl(courseId), {
    ...options,
    method: "GET",
  });
};

export const getListVideosQueryKey = (courseId: number) => {
  return [`/api/courses/${courseId}/videos`] as const;
};

export const getListVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVideosQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({
    signal,
  }) => listVideos(courseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!courseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listVideos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVideos>>
>;
export type ListVideosQueryError = ErrorType<unknown>;

/**
 * @summary List videos for a course
 */

export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListVideosQueryOptions(courseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a video to a course (admin)
 */
export const getCreateVideoUrl = (courseId: number) => {
  return `/api/courses/${courseId}/videos`;
};

export const createVideo = async (
  courseId: number,
  createVideoBody: CreateVideoBody,
  options?: RequestInit,
): Promise<Video> => {
  return customFetch<Video>(getCreateVideoUrl(courseId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createVideoBody),
  });
};

export const getCreateVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { courseId: number; data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { courseId: number; data: BodyType<CreateVideoBody> },
  TContext
> => {
  const mutationKey = ["createVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVideo>>,
    { courseId: number; data: BodyType<CreateVideoBody> }
  > = (props) => {
    const { courseId, data } = props ?? {};

    return createVideo(courseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof createVideo>>
>;
export type CreateVideoMutationBody = BodyType<CreateVideoBody>;
export type CreateVideoMutationError = ErrorType<unknown>;

/**
 * @summary Add a video to a course (admin)
 */
export const useCreateVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { courseId: number; data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { courseId: number; data: BodyType<CreateVideoBody> },
  TContext
> => {
  return useMutation(getCreateVideoMutationOptions(options));
};

/**
 * @summary Get a video
 */
export const getGetVideoUrl = (id: number) => {
  return `/api/videos/${id}`;
};

export const getVideo = async (
  id: number,
  options?: RequestInit,
): Promise<Video> => {
  return customFetch<Video>(getGetVideoUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetVideoQueryKey = (id: number) => {
  return [`/api/videos/${id}`] as const;
};

export const getGetVideoQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideo>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVideo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideo>>> = ({
    signal,
  }) => getVideo(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getVideo>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetVideoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideo>>
>;
export type GetVideoQueryError = ErrorType<unknown>;

/**
 * @summary Get a video
 */

export function useGetVideo<
  TData = Awaited<ReturnType<typeof getVideo>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVideo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetVideoQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a video (admin)
 */
export const getDeleteVideoUrl = (id: number) => {
  return `/api/videos/${id}`;
};

export const deleteVideo = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteVideoUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVideo>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteVideo(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVideo>>
>;

export type DeleteVideoMutationError = ErrorType<unknown>;

/**
 * @summary Delete a video (admin)
 */
export const useDeleteVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteVideoMutationOptions(options));
};

/**
 * @summary List PDFs for a course
 */
export const getListPdfsUrl = (courseId: number) => {
  return `/api/courses/${courseId}/pdfs`;
};

export const listPdfs = async (
  courseId: number,
  options?: RequestInit,
): Promise<Pdf[]> => {
  return customFetch<Pdf[]>(getListPdfsUrl(courseId), {
    ...options,
    method: "GET",
  });
};

export const getListPdfsQueryKey = (courseId: number) => {
  return [`/api/courses/${courseId}/pdfs`] as const;
};

export const getListPdfsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPdfs>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPdfs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPdfsQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPdfs>>> = ({
    signal,
  }) => listPdfs(courseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!courseId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listPdfs>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type ListPdfsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPdfs>>
>;
export type ListPdfsQueryError = ErrorType<unknown>;

/**
 * @summary List PDFs for a course
 */

export function useListPdfs<
  TData = Awaited<ReturnType<typeof listPdfs>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPdfs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListPdfsQueryOptions(courseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a PDF to a course (admin)
 */
export const getCreatePdfUrl = (courseId: number) => {
  return `/api/courses/${courseId}/pdfs`;
};

export const createPdf = async (
  courseId: number,
  createPdfBody: CreatePdfBody,
  options?: RequestInit,
): Promise<Pdf> => {
  return customFetch<Pdf>(getCreatePdfUrl(courseId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPdfBody),
  });
};

export const getCreatePdfMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPdf>>,
    TError,
    { courseId: number; data: BodyType<CreatePdfBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPdf>>,
  TError,
  { courseId: number; data: BodyType<CreatePdfBody> },
  TContext
> => {
  const mutationKey = ["createPdf"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPdf>>,
    { courseId: number; data: BodyType<CreatePdfBody> }
  > = (props) => {
    const { courseId, data } = props ?? {};

    return createPdf(courseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePdfMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPdf>>
>;
export type CreatePdfMutationBody = BodyType<CreatePdfBody>;
export type CreatePdfMutationError = ErrorType<unknown>;

/**
 * @summary Add a PDF to a course (admin)
 */
export const useCreatePdf = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPdf>>,
    TError,
    { courseId: number; data: BodyType<CreatePdfBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPdf>>,
  TError,
  { courseId: number; data: BodyType<CreatePdfBody> },
  TContext
> => {
  return useMutation(getCreatePdfMutationOptions(options));
};

/**
 * @summary List test series
 */
export const getListTestSeriesUrl = (params?: ListTestSeriesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/test-series?${stringifiedParams}`
    : `/api/test-series`;
};

export const listTestSeries = async (
  params?: ListTestSeriesParams,
  options?: RequestInit,
): Promise<TestSeries[]> => {
  return customFetch<TestSeries[]>(getListTestSeriesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListTestSeriesQueryKey = (params?: ListTestSeriesParams) => {
  return [`/api/test-series`, ...(params ? [params] : [])] as const;
};

export const getListTestSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof listTestSeries>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTestSeriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTestSeries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTestSeriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTestSeries>>> = ({
    signal,
  }) => listTestSeries(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTestSeries>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTestSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTestSeries>>
>;
export type ListTestSeriesQueryError = ErrorType<unknown>;

/**
 * @summary List test series
 */

export function useListTestSeries<
  TData = Awaited<ReturnType<typeof listTestSeries>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTestSeriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTestSeries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTestSeriesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a test series (admin)
 */
export const getCreateTestSeriesUrl = () => {
  return `/api/test-series`;
};

export const createTestSeries = async (
  createTestSeriesBody: CreateTestSeriesBody,
  options?: RequestInit,
): Promise<TestSeries> => {
  return customFetch<TestSeries>(getCreateTestSeriesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTestSeriesBody),
  });
};

export const getCreateTestSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTestSeries>>,
    TError,
    { data: BodyType<CreateTestSeriesBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTestSeries>>,
  TError,
  { data: BodyType<CreateTestSeriesBody> },
  TContext
> => {
  const mutationKey = ["createTestSeries"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTestSeries>>,
    { data: BodyType<CreateTestSeriesBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createTestSeries(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTestSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTestSeries>>
>;
export type CreateTestSeriesMutationBody = BodyType<CreateTestSeriesBody>;
export type CreateTestSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Create a test series (admin)
 */
export const useCreateTestSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTestSeries>>,
    TError,
    { data: BodyType<CreateTestSeriesBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTestSeries>>,
  TError,
  { data: BodyType<CreateTestSeriesBody> },
  TContext
> => {
  return useMutation(getCreateTestSeriesMutationOptions(options));
};

/**
 * @summary Get test series with questions
 */
export const getGetTestSeriesUrl = (id: number) => {
  return `/api/test-series/${id}`;
};

export const getTestSeries = async (
  id: number,
  options?: RequestInit,
): Promise<TestSeriesDetail> => {
  return customFetch<TestSeriesDetail>(getGetTestSeriesUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetTestSeriesQueryKey = (id: number) => {
  return [`/api/test-series/${id}`] as const;
};

export const getGetTestSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getTestSeries>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTestSeries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTestSeriesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTestSeries>>> = ({
    signal,
  }) => getTestSeries(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTestSeries>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTestSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTestSeries>>
>;
export type GetTestSeriesQueryError = ErrorType<unknown>;

/**
 * @summary Get test series with questions
 */

export function useGetTestSeries<
  TData = Awaited<ReturnType<typeof getTestSeries>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTestSeries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTestSeriesQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List DPPs for a course
 */
export const getListDppsUrl = (courseId: number) => {
  return `/api/courses/${courseId}/dpps`;
};

export const listDpps = async (
  courseId: number,
  options?: RequestInit,
): Promise<Dpp[]> => {
  return customFetch<Dpp[]>(getListDppsUrl(courseId), {
    ...options,
    method: "GET",
  });
};

export const getListDppsQueryKey = (courseId: number) => {
  return [`/api/courses/${courseId}/dpps`] as const;
};

export const getListDppsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDpps>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDpps>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDppsQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDpps>>> = ({
    signal,
  }) => listDpps(courseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!courseId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listDpps>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type ListDppsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDpps>>
>;
export type ListDppsQueryError = ErrorType<unknown>;

/**
 * @summary List DPPs for a course
 */

export function useListDpps<
  TData = Awaited<ReturnType<typeof listDpps>>,
  TError = ErrorType<unknown>,
>(
  courseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDpps>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDppsQueryOptions(courseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a DPP to a course (admin)
 */
export const getCreateDppUrl = (courseId: number) => {
  return `/api/courses/${courseId}/dpps`;
};

export const createDpp = async (
  courseId: number,
  createDppBody: CreateDppBody,
  options?: RequestInit,
): Promise<Dpp> => {
  return customFetch<Dpp>(getCreateDppUrl(courseId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createDppBody),
  });
};

export const getCreateDppMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDpp>>,
    TError,
    { courseId: number; data: BodyType<CreateDppBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDpp>>,
  TError,
  { courseId: number; data: BodyType<CreateDppBody> },
  TContext
> => {
  const mutationKey = ["createDpp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDpp>>,
    { courseId: number; data: BodyType<CreateDppBody> }
  > = (props) => {
    const { courseId, data } = props ?? {};

    return createDpp(courseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDppMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDpp>>
>;
export type CreateDppMutationBody = BodyType<CreateDppBody>;
export type CreateDppMutationError = ErrorType<unknown>;

/**
 * @summary Add a DPP to a course (admin)
 */
export const useCreateDpp = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDpp>>,
    TError,
    { courseId: number; data: BodyType<CreateDppBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createDpp>>,
  TError,
  { courseId: number; data: BodyType<CreateDppBody> },
  TContext
> => {
  return useMutation(getCreateDppMutationOptions(options));
};

/**
 * @summary List live streams
 */
export const getListLiveStreamsUrl = () => {
  return `/api/live-streams`;
};

export const listLiveStreams = async (
  options?: RequestInit,
): Promise<LiveStream[]> => {
  return customFetch<LiveStream[]>(getListLiveStreamsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListLiveStreamsQueryKey = () => {
  return [`/api/live-streams`] as const;
};

export const getListLiveStreamsQueryOptions = <
  TData = Awaited<ReturnType<typeof listLiveStreams>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listLiveStreams>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListLiveStreamsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listLiveStreams>>> = ({
    signal,
  }) => listLiveStreams({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listLiveStreams>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListLiveStreamsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listLiveStreams>>
>;
export type ListLiveStreamsQueryError = ErrorType<unknown>;

/**
 * @summary List live streams
 */

export function useListLiveStreams<
  TData = Awaited<ReturnType<typeof listLiveStreams>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listLiveStreams>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListLiveStreamsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a live stream (admin)
 */
export const getCreateLiveStreamUrl = () => {
  return `/api/live-streams`;
};

export const createLiveStream = async (
  createLiveStreamBody: CreateLiveStreamBody,
  options?: RequestInit,
): Promise<LiveStream> => {
  return customFetch<LiveStream>(getCreateLiveStreamUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createLiveStreamBody),
  });
};

export const getCreateLiveStreamMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLiveStream>>,
    TError,
    { data: BodyType<CreateLiveStreamBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLiveStream>>,
  TError,
  { data: BodyType<CreateLiveStreamBody> },
  TContext
> => {
  const mutationKey = ["createLiveStream"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLiveStream>>,
    { data: BodyType<CreateLiveStreamBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createLiveStream(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLiveStreamMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLiveStream>>
>;
export type CreateLiveStreamMutationBody = BodyType<CreateLiveStreamBody>;
export type CreateLiveStreamMutationError = ErrorType<unknown>;

/**
 * @summary Create a live stream (admin)
 */
export const useCreateLiveStream = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLiveStream>>,
    TError,
    { data: BodyType<CreateLiveStreamBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createLiveStream>>,
  TError,
  { data: BodyType<CreateLiveStreamBody> },
  TContext
> => {
  return useMutation(getCreateLiveStreamMutationOptions(options));
};

/**
 * @summary Get a live stream
 */
export const getGetLiveStreamUrl = (id: number) => {
  return `/api/live-streams/${id}`;
};

export const getLiveStream = async (
  id: number,
  options?: RequestInit,
): Promise<LiveStream> => {
  return customFetch<LiveStream>(getGetLiveStreamUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetLiveStreamQueryKey = (id: number) => {
  return [`/api/live-streams/${id}`] as const;
};

export const getGetLiveStreamQueryOptions = <
  TData = Awaited<ReturnType<typeof getLiveStream>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLiveStream>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLiveStreamQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveStream>>> = ({
    signal,
  }) => getLiveStream(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLiveStream>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLiveStreamQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLiveStream>>
>;
export type GetLiveStreamQueryError = ErrorType<unknown>;

/**
 * @summary Get a live stream
 */

export function useGetLiveStream<
  TData = Awaited<ReturnType<typeof getLiveStream>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLiveStream>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLiveStreamQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a live stream (admin)
 */
export const getUpdateLiveStreamUrl = (id: number) => {
  return `/api/live-streams/${id}`;
};

export const updateLiveStream = async (
  id: number,
  updateLiveStreamBody: UpdateLiveStreamBody,
  options?: RequestInit,
): Promise<LiveStream> => {
  return customFetch<LiveStream>(getUpdateLiveStreamUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateLiveStreamBody),
  });
};

export const getUpdateLiveStreamMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLiveStream>>,
    TError,
    { id: number; data: BodyType<UpdateLiveStreamBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLiveStream>>,
  TError,
  { id: number; data: BodyType<UpdateLiveStreamBody> },
  TContext
> => {
  const mutationKey = ["updateLiveStream"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLiveStream>>,
    { id: number; data: BodyType<UpdateLiveStreamBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateLiveStream(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLiveStreamMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLiveStream>>
>;
export type UpdateLiveStreamMutationBody = BodyType<UpdateLiveStreamBody>;
export type UpdateLiveStreamMutationError = ErrorType<unknown>;

/**
 * @summary Update a live stream (admin)
 */
export const useUpdateLiveStream = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLiveStream>>,
    TError,
    { id: number; data: BodyType<UpdateLiveStreamBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateLiveStream>>,
  TError,
  { id: number; data: BodyType<UpdateLiveStreamBody> },
  TContext
> => {
  return useMutation(getUpdateLiveStreamMutationOptions(options));
};

/**
 * @summary List current user enrollments
 */
export const getListEnrollmentsUrl = () => {
  return `/api/enrollments`;
};

export const listEnrollments = async (
  options?: RequestInit,
): Promise<Enrollment[]> => {
  return customFetch<Enrollment[]>(getListEnrollmentsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListEnrollmentsQueryKey = () => {
  return [`/api/enrollments`] as const;
};

export const getListEnrollmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listEnrollments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listEnrollments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListEnrollmentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listEnrollments>>> = ({
    signal,
  }) => listEnrollments({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listEnrollments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListEnrollmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listEnrollments>>
>;
export type ListEnrollmentsQueryError = ErrorType<unknown>;

/**
 * @summary List current user enrollments
 */

export function useListEnrollments<
  TData = Awaited<ReturnType<typeof listEnrollments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listEnrollments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListEnrollmentsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Enroll in a course
 */
export const getEnrollUrl = () => {
  return `/api/enrollments`;
};

export const enroll = async (
  enrollBody: EnrollBody,
  options?: RequestInit,
): Promise<Enrollment> => {
  return customFetch<Enrollment>(getEnrollUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(enrollBody),
  });
};

export const getEnrollMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof enroll>>,
    TError,
    { data: BodyType<EnrollBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof enroll>>,
  TError,
  { data: BodyType<EnrollBody> },
  TContext
> => {
  const mutationKey = ["enroll"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof enroll>>,
    { data: BodyType<EnrollBody> }
  > = (props) => {
    const { data } = props ?? {};

    return enroll(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EnrollMutationResult = NonNullable<
  Awaited<ReturnType<typeof enroll>>
>;
export type EnrollMutationBody = BodyType<EnrollBody>;
export type EnrollMutationError = ErrorType<unknown>;

/**
 * @summary Enroll in a course
 */
export const useEnroll = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof enroll>>,
    TError,
    { data: BodyType<EnrollBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof enroll>>,
  TError,
  { data: BodyType<EnrollBody> },
  TContext
> => {
  return useMutation(getEnrollMutationOptions(options));
};

/**
 * @summary Get dashboard statistics
 */
export const getGetDashboardStatsUrl = () => {
  return `/api/dashboard/stats`;
};

export const getDashboardStats = async (
  options?: RequestInit,
): Promise<DashboardStats> => {
  return customFetch<DashboardStats>(getGetDashboardStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDashboardStatsQueryKey = () => {
  return [`/api/dashboard/stats`] as const;
};

export const getGetDashboardStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardStats>>
  > = ({ signal }) => getDashboardStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDashboardStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardStats>>
>;
export type GetDashboardStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get dashboard statistics
 */

export function useGetDashboardStats<
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get recent platform activity
 */
export const getGetRecentActivityUrl = () => {
  return `/api/dashboard/recent-activity`;
};

export const getRecentActivity = async (
  options?: RequestInit,
): Promise<ActivityItem[]> => {
  return customFetch<ActivityItem[]>(getGetRecentActivityUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRecentActivityQueryKey = () => {
  return [`/api/dashboard/recent-activity`] as const;
};

export const getGetRecentActivityQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentActivity>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecentActivityQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentActivity>>
  > = ({ signal }) => getRecentActivity({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRecentActivityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentActivity>>
>;
export type GetRecentActivityQueryError = ErrorType<unknown>;

/**
 * @summary Get recent platform activity
 */

export function useGetRecentActivity<
  TData = Awaited<ReturnType<typeof getRecentActivity>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRecentActivity>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRecentActivityQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
