/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Swayam Shiksha API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
}

export interface RegisterBody {
  name: string;
  email: string;
  password: string;
  /** @nullable */
  phone?: string | null;
}

export interface LoginBody {
  email: string;
  password: string;
}

export interface AuthUser {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  role: string;
  /** @nullable */
  avatarUrl?: string | null;
  createdAt: string;
}

export interface Category {
  id: number;
  name: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  iconUrl?: string | null;
  color: string;
  courseCount: number;
  createdAt: string;
}

export interface CreateCategoryBody {
  name: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  iconUrl?: string | null;
  color: string;
}

export interface UpdateCategoryBody {
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  iconUrl?: string | null;
  color?: string;
}

export interface Course {
  id: number;
  title: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  categoryId: number;
  categoryName: string;
  price: number;
  isFree: boolean;
  isFeatured: boolean;
  language: string;
  level: string;
  totalVideos: number;
  totalPdfs: number;
  totalDpps: number;
  enrollmentCount: number;
  instructorName: string;
  createdAt: string;
}

export interface CourseDetail {
  id: number;
  title: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  categoryId: number;
  categoryName: string;
  price: number;
  isFree: boolean;
  isFeatured: boolean;
  language: string;
  level: string;
  totalVideos: number;
  totalPdfs: number;
  totalDpps: number;
  enrollmentCount: number;
  instructorName: string;
  createdAt: string;
  isEnrolled: boolean;
}

export interface CreateCourseBody {
  title: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  categoryId: number;
  price: number;
  isFree: boolean;
  isFeatured?: boolean;
  language: string;
  level: string;
  instructorName: string;
}

export interface UpdateCourseBody {
  title?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  price?: number;
  isFree?: boolean;
  isFeatured?: boolean;
  language?: string;
  level?: string;
  instructorName?: string;
}

export interface Video {
  id: number;
  courseId: number;
  title: string;
  /** @nullable */
  description?: string | null;
  videoUrl: string;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  duration?: number | null;
  orderIndex: number;
  isFree: boolean;
  createdAt: string;
}

export interface CreateVideoBody {
  title: string;
  /** @nullable */
  description?: string | null;
  videoUrl: string;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  duration?: number | null;
  orderIndex: number;
  isFree?: boolean;
}

export interface Pdf {
  id: number;
  courseId: number;
  title: string;
  /** @nullable */
  description?: string | null;
  pdfUrl: string;
  /** @nullable */
  fileSize?: number | null;
  orderIndex: number;
  isFree: boolean;
  createdAt: string;
}

export interface CreatePdfBody {
  title: string;
  /** @nullable */
  description?: string | null;
  pdfUrl: string;
  /** @nullable */
  fileSize?: number | null;
  orderIndex: number;
  isFree?: boolean;
}

export interface TestSeries {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  categoryId?: number | null;
  /** @nullable */
  categoryName?: string | null;
  totalQuestions: number;
  durationMinutes: number;
  isFree: boolean;
  difficulty: string;
  createdAt: string;
}

export interface TestQuestion {
  id: number;
  testSeriesId: number;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: string;
  /** @nullable */
  explanation?: string | null;
  orderIndex: number;
}

export interface TestSeriesDetail {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  categoryId?: number | null;
  /** @nullable */
  categoryName?: string | null;
  totalQuestions: number;
  durationMinutes: number;
  isFree: boolean;
  difficulty: string;
  questions: TestQuestion[];
  createdAt: string;
}

export interface CreateTestSeriesBody {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  categoryId?: number | null;
  durationMinutes: number;
  isFree?: boolean;
  difficulty: string;
}

export interface Dpp {
  id: number;
  courseId: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  pdfUrl?: string | null;
  /** @nullable */
  solutionUrl?: string | null;
  totalQuestions: number;
  orderIndex: number;
  createdAt: string;
}

export interface CreateDppBody {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  pdfUrl?: string | null;
  /** @nullable */
  solutionUrl?: string | null;
  totalQuestions: number;
  orderIndex: number;
}

export interface LiveStream {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  streamUrl?: string | null;
  instructorName: string;
  /** @nullable */
  categoryId?: number | null;
  /** @nullable */
  categoryName?: string | null;
  scheduledAt: string;
  status: string;
  viewerCount: number;
  createdAt: string;
}

export interface CreateLiveStreamBody {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  streamUrl?: string | null;
  instructorName: string;
  /** @nullable */
  categoryId?: number | null;
  scheduledAt: string;
  status: string;
}

export interface UpdateLiveStreamBody {
  title?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  streamUrl?: string | null;
  status?: string;
  viewerCount?: number;
}

export interface Enrollment {
  id: number;
  userId: number;
  courseId: number;
  courseTitle: string;
  /** @nullable */
  courseThumbnailUrl?: string | null;
  enrolledAt: string;
  progress: number;
}

export interface EnrollBody {
  courseId: number;
}

export interface DashboardStats {
  totalCourses: number;
  totalStudents: number;
  totalVideos: number;
  totalLiveStreams: number;
  totalTestSeries: number;
  activeStreams: number;
  enrolledCourses: number;
  recentEnrollments: number;
}

export interface ActivityItem {
  id: number;
  type: string;
  title: string;
  subtitle: string;
  createdAt: string;
}

export type ListCoursesParams = {
  categoryId?: number;
  featured?: boolean;
};

export type ListTestSeriesParams = {
  categoryId?: number;
};
